### ISSUE TITLE
[1.16.5] Reload questing config on-the-go

### ISSUE THREAD

**Issue by ChromaPIE** [henkelmax/delivery-questing#1]
**Is your feature request related to a problem? Please describe.**
I've noticed that it's required to quit current world and re-enter it to apply changes in everything under config/delivery. It is a bit annoying, a reload support may handle this kind of situation.

**Describe the solution you'd like**
Vanilla /reload, or a newly-introduced standalone reload command reloads things under config/delivery.

**Describe alternatives you've considered**
Yea I am totally able to simply perform an out&in. However a command will be better.

**Additional context**
By the way I'm kinda confused by the "id"s. Is it fully customizable or I have to follow D.Inc.'s structure like `edb577e0-608e-11eb-ae93-000000000001`? Or there are actually some kind of fixed syntax?

**Comment by henkelmax** [comment]
It is not possible to reload it while ingame, since a lot of stuff depends on the quests. If quests would disappear while still in game, a lot of stuff would break or even crash. It's not even recommended to join a world where a quest was loaded that has been removed.

**Comment by ChromaPIE** [comment]
Fair enough. And how about the ID? There must be a format to follow but I'm not sure.

**Comment by henkelmax** [comment]
It just has to be unique

**Comment by ChromaPIE** [comment]
I have done a try. I simply gave a 001 as a task id then it crashed.

**Comment by henkelmax** [comment]
because it has to be a valid UUID

**Comment by ChromaPIE** [comment]
Okay got it. Thanks for the support!
