### ISSUE TITLE
Per-task or global parameter to use picture as avatar instead of skins

### ISSUE THREAD

**Issue by ChromaPIE** [henkelmax/delivery-questing#2]
**Is your feature request related to a problem? Please describe.**
Using pictures (generated with https://thispersondoesnotexist.com/ maybe) instead of skins on models may fit better with packs with a more realistic theme and background.

**Describe the solution you'd like**
An additional key in tasks to make it directly render the picture in the avatar section instead of force it on a player model, or any other solutions cuz I'm too dumb.

**Comment by henkelmax** [comment]
Won't happen. This is as far away from Minecraft as it can get. This won't fit into this mod at all.
