### ISSUE TITLE
Long descriptions go out of the GUI

### ISSUE THREAD

**Issue by ChromaPIE** [henkelmax/delivery-questing#3]
**Bug description**
The GUI for both bulletin boards and computers lacks something like a scroll bar to handle long descriptions, instead they go out of the GUI border.

**Expected behavior**
A scroll bar for both GUIs to handle long descriptions

**Comment by henkelmax** [comment]
There won't be a scroll bar. Descriptions should always be short enough to fit on the screen.

**Comment by ChromaPIE** [comment]
Okay. As long as you think a bunch of quests with one or two lines saying i want this i want that and nothing more are fun enough.
