### ISSUE TITLE
Ticking Memory Crash

### ISSUE THREAD

**Issue by teagan75** [henkelmax/delivery-questing#4]
**Bug description**
I get a ticking memory crash when I load only ten quests. When I add all the quests from your example in your source code it loads fine. I validated my json too and nothing is wrong with my ids or syntax. etc. 

**Expected behavior**
I expect my world to load no matter how many quests are written. My question is do I need a certain amount of quests written before I can load it into a world?

**Log files**
https://pastebin.com/UGhAaq9J
[2022-10-28-7.log](https://github.com/henkelmax/delivery-questing/files/9892644/2022-10-28-7.log)

**Versions**
- Minecraft version 1.16.5
- Forge version 36.2.39
- Mod version 1.16.5-1.0.45

**Other mods**
found in crash report

**Screenshots (Optional)**
Screenshots of the issue.

**Comment by henkelmax** [comment]
This version is no longer maintained.

**Comment by teagan75** [comment]
Would you be able to at least answer my question for this version? How many quests do I need written before it will no longer crash?

**Comment by henkelmax** [comment]
No clue what you mean. This mod was created for a specific modpack. There is no documentation for the mos.
